# Generated by Django 4.1.2 on 2022-10-13 13:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goods',
            old_name='goods',
            new_name='goods_expenses',
        ),
        migrations.AddField(
            model_name='goods',
            name='goods_savings',
            field=models.CharField(default=False, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='expenses',
            name='time_expenses',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 13, 16, 21, 22, 478287)),
        ),
        migrations.AlterField(
            model_name='savings',
            name='time_saving',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 13, 16, 21, 22, 477269)),
        ),
    ]
