# Generated by Django 4.1.2 on 2022-10-14 09:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0005_alter_expenses_time_expenses_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='time_expenses',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 14, 12, 3, 4, 16288)),
        ),
        migrations.AlterField(
            model_name='goods',
            name='goods_expenses',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='goods',
            name='goods_savings',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='savings',
            name='time_saving',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 14, 12, 3, 4, 16288)),
        ),
    ]
