# Generated by Django 4.1.2 on 2022-11-07 12:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0008_alter_expenses_time_expenses_alter_expenses_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='sum',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='time_expenses',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 7, 15, 0, 11, 909033)),
        ),
        migrations.AlterField(
            model_name='savings',
            name='sum',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='savings',
            name='time_saving',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 7, 15, 0, 11, 909033)),
        ),
    ]
