# Generated by Django 4.1.2 on 2022-11-07 16:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0011_alter_expenses_time_expenses_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expenses',
            old_name='good_expenses',
            new_name='good_expense',
        ),
        migrations.AlterField(
            model_name='expenses',
            name='time_expenses',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 7, 19, 38, 6, 397231)),
        ),
        migrations.AlterField(
            model_name='savings',
            name='time_saving',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 7, 19, 38, 6, 396223)),
        ),
    ]
